# Generated by Django 3.2.18 on 2023-03-09 01:48

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='servico', variations={'thumb': {'crop': True, 'height': 380, 'width': 480}}, verbose_name='Imagem'),
        ),
    ]
